export const states = {
  AL: {
    name: "Alabama",
    abbreviation: "AL",
    state: true,
    numberOfDelegates: 7,
    houseName: "House of Representatives",
    houseRepName: "Representative",
    senateName: "Senate",
    senatorName: "Senator",
  },
  AK: {
    name: "Alaska",
    abbreviation: "AK",
    state: true,
    numberOfDelegates: 1,
    houseName: "House of Representatives",
    houseRepName: "Representative",
    senateName: "Senate",
    senatorName: "Senator",
  },
  AZ: {
    name: "Arizona",
    abbreviation: "AZ",
    state: true,
    numberOfDelegates: 9,
    houseName: "House of Representatives",
    houseRepName: "Representative",
    senateName: "Senate",
    senatorName: "Senator",
  },
  AR: {
    name: "Arkansas",
    abbreviation: "AR",
    state: true,
    numberOfDelegates: 4,
    houseName: "House of Representatives",
    houseRepName: "Representative",
    senateName: "Senate",
    senatorName: "Senator",
  },
  CA: {
    name: "California",
    abbreviation: "CA",
    state: true,
    numberOfDelegates: 52,
    houseName: "State Assembly",
    houseRepName: "Assemblymember",
    senateName: "State Senate",
    senatorName: "Senator",
  },
  CO: {
    name: "Colorado",
    abbreviation: "CO",
    state: true,
    numberOfDelegates: 7,
    houseName: "House of Representatives",
    houseRepName: "Representative",
    senateName: "Senate",
    senatorName: "Senator",
  },
  CT: {
    name: "Connecticut",
    abbreviation: "CT",
    state: true,
    numberOfDelegates: 5,
    houseName: "House of Representatives",
    houseRepName: "Representative",
    senateName: "Senate",
    senatorName: "Senator",
  },
  DE: {
    name: "Delaware",
    abbreviation: "DE",
    state: true,
    numberOfDelegates: 1,
    houseName: "House of Representatives",
    houseRepName: "Representative",
    senateName: "Senate",
    senatorName: "Senator",
  },
  DC: {
    name: "District of Columbia",
    abbreviation: "DC",
    state: false,
    numberOfDelegates: 1,
    houseName: "Council of the District of Columbia",
    houseRepName: "Councilmember",
    senateName: null,
    senatorName: null,
  },
  FL: {
    name: "Florida",
    abbreviation: "FL",
    state: true,
    numberOfDelegates: 27,
    houseName: "House of Representatives",
    houseRepName: "Representative",
    senateName: "Senate",
    senatorName: "Senator",
  },
  GA: {
    name: "Georgia",
    abbreviation: "GA",
    state: true,
    numberOfDelegates: 14,
    houseName: "House of Representatives",
    houseRepName: "Representative",
    senateName: "Senate",
    senatorName: "Senator",
  },
  GU: {
    name: "Guam",
    abbreviation: "GU",
    state: false,
    numberOfDelegates: 1,
    houseName: "Guam Legislature",
    houseRepName: "Senator",
    senateName: null,
    senatorName: null,
  },
  HI: {
    name: "Hawaii",
    abbreviation: "HI",
    state: true,
    numberOfDelegates: 2,
    houseName: "House of Representatives",
    houseRepName: "Representative",
    senateName: "Senate",
    senatorName: "Senator",
  },
  ID: {
    name: "Idaho",
    abbreviation: "ID",
    state: true,
    numberOfDelegates: 2,
    houseName: "House of Representatives",
    houseRepName: "Representative",
    senateName: "Senate",
    senatorName: "Senator",
  },
  IL: {
    name: "Illinois",
    abbreviation: "IL",
    state: true,
    numberOfDelegates: 18,
    houseName: "House of Representatives",
    houseRepName: "Representative",
    senateName: "Senate",
    senatorName: "Senator",
  },
  IN: {
    name: "Indiana",
    abbreviation: "IN",
    state: true,
    numberOfDelegates: 9,
    houseName: "House of Representatives",
    houseRepName: "Representative",
    senateName: "Senate",
    senatorName: "Senator",
  },
  IA: {
    name: "Iowa",
    abbreviation: "IA",
    state: true,
    numberOfDelegates: 4,
    houseName: "House of Representatives",
    houseRepName: "Representative",
    senateName: "Senate",
    senatorName: "Senator",
  },
  KS: {
    name: "Kansas",
    abbreviation: "KS",
    state: true,
    numberOfDelegates: 4,
    houseName: "House of Representatives",
    houseRepName: "Representative",
    senateName: "Senate",
    senatorName: "Senator",
  },
  KY: {
    name: "Kentucky",
    abbreviation: "KY",
    state: true,
    numberOfDelegates: 6,
    houseName: "House of Representatives",
    houseRepName: "Representative",
    senateName: "Senate",
    senatorName: "Senator",
  },
  LA: {
    name: "Louisiana",
    abbreviation: "LA",
    state: true,
    numberOfDelegates: 6,
    houseName: "House of Representatives",
    houseRepName: "Representative",
    senateName: "Senate",
    senatorName: "Senator",
  },
  ME: {
    name: "Maine",
    abbreviation: "ME",
    state: true,
    numberOfDelegates: 2,
    houseName: "House of Representatives",
    houseRepName: "Representative",
    senateName: "Senate",
    senatorName: "Senator",
  },
  MD: {
    name: "Maryland",
    abbreviation: "MD",
    state: true,
    numberOfDelegates: 8,
    houseName: "House of Delegates",
    houseRepName: "Delegate",
    senateName: "Senate",
    senatorName: "Senator",
  },
  MA: {
    name: "Massachusetts",
    abbreviation: "MA",
    state: true,
    numberOfDelegates: 9,
    houseName: "House of Representatives",
    houseRepName: "Representative",
    senateName: "Senate",
    senatorName: "Senator",
  },
  MI: {
    name: "Michigan",
    abbreviation: "MI",
    state: true,
    numberOfDelegates: 14,
    houseName: "House of Representatives",
    houseRepName: "Representative",
    senateName: "Senate",
    senatorName: "Senator",
  },
  MN: {
    name: "Minnesota",
    abbreviation: "MN",
    state: true,
    numberOfDelegates: 8,
    houseName: "House of Representatives",
    houseRepName: "Representative",
    senateName: "Senate",
    senatorName: "Senator",
  },
  MS: {
    name: "Mississippi",
    abbreviation: "MS",
    state: true,
    numberOfDelegates: 4,
    houseName: "House of Representatives",
    houseRepName: "Representative",
    senateName: "Senate",
    senatorName: "Senator",
  },
  MO: {
    name: "Missouri",
    abbreviation: "MO",
    state: true,
    numberOfDelegates: 8,
    houseName: "House of Representatives",
    houseRepName: "Representative",
    senateName: "Senate",
    senatorName: "Senator",
  },
  MT: {
    name: "Montana",
    abbreviation: "MT",
    state: true,
    numberOfDelegates: 1,
    houseName: "House of Representatives",
    houseRepName: "Representative",
    senateName: "Senate",
    senatorName: "Senator",
  },
  NE: {
    name: "Nebraska",
    abbreviation: "NE",
    state: true,
    numberOfDelegates: 3,
    houseName: "Unicameral Legislature",
    houseRepName: "Senator",
    senateName: null,
    senatorName: null,
  },
  NV: {
    name: "Nevada",
    abbreviation: "NV",
    state: true,
    numberOfDelegates: 4,
    houseName: "Assembly",
    houseRepName: "Assemblymember",
    senateName: "Senate",
    senatorName: "Senator",
  },
  NH: {
    name: "New Hampshire",
    abbreviation: "NH",
    state: true,
    numberOfDelegates: 2,
    houseName: "House of Representatives",
    houseRepName: "Representative",
    senateName: "Senate",
    senatorName: "Senator",
  },
  NJ: {
    name: "New Jersey",
    abbreviation: "NJ",
    state: true,
    numberOfDelegates: 12,
    houseName: "General Assembly",
    houseRepName: "Assemblymember",
    senateName: "Senate",
    senatorName: "Senator",
  },
  NM: {
    name: "New Mexico",
    abbreviation: "NM",
    state: true,
    numberOfDelegates: 3,
    houseName: "House of Representatives",
    houseRepName: "Representative",
    senateName: "Senate",
    senatorName: "Senator",
  },
  NY: {
    name: "New York",
    abbreviation: "NY",
    state: true,
    numberOfDelegates: 26,
    houseName: "State Assembly",
    houseRepName: "Assemblymember",
    senateName: "State Senate",
    senatorName: "Senator",
  },
  NC: {
    name: "North Carolina",
    abbreviation: "NC",
    state: true,
    numberOfDelegates: 14,
    houseName: "House of Representatives",
    houseRepName: "Representative",
    senateName: "Senate",
    senatorName: "Senator",
  },
  ND: {
    name: "North Dakota",
    abbreviation: "ND",
    state: true,
    numberOfDelegates: 1,
    houseName: "House of Representatives",
    houseRepName: "Representative",
    senateName: "Senate",
    senatorName: "Senator",
  },
  MP: {
    name: "Northern Mariana Islands",
    abbreviation: "MP",
    state: false,
    numberOfDelegates: 1,
    houseName: "House of Representatives",
    houseRepName: "Representative",
    senateName: null,
    senatorName: null,
  },
  OH: {
    name: "Ohio",
    abbreviation: "OH",
    state: true,
    numberOfDelegates: 15,
    houseName: "House of Representatives",
    houseRepName: "Representative",
    senateName: "Senate",
    senatorName: "Senator",
  },
  OK: {
    name: "Oklahoma",
    abbreviation: "OK",
    state: true,
    numberOfDelegates: 5,
    houseName: "House of Representatives",
    houseRepName: "Representative",
    senateName: "Senate",
    senatorName: "Senator",
  },
  OR: {
    name: "Oregon",
    abbreviation: "OR",
    state: true,
    numberOfDelegates: 6,
    houseName: "House of Representatives",
    houseRepName: "Representative",
    senateName: "Senate",
    senatorName: "Senator",
  },
  PA: {
    name: "Pennsylvania",
    abbreviation: "PA",
    state: true,
    numberOfDelegates: 17,
    houseName: "House of Representatives",
    houseRepName: "Representative",
    senateName: "Senate",
    senatorName: "Senator",
  },
  PR: {
    name: "Puerto Rico",
    abbreviation: "PR",
    state: false,
    numberOfDelegates: 1,
    houseName: "House of Representatives",
    houseRepName: "Representative",
    senateName: "Senate",
    senatorName: "Senator",
  },
  RI: {
    name: "Rhode Island",
    abbreviation: "RI",
    state: true,
    numberOfDelegates: 2,
    houseName: "House of Representatives",
    houseRepName: "Representative",
    senateName: "Senate",
    senatorName: "Senator",
  },
  SC: {
    name: "South Carolina",
    abbreviation: "SC",
    state: true,
    numberOfDelegates: 7,
    houseName: "House of Representatives",
    houseRepName: "Representative",
    senateName: "Senate",
    senatorName: "Senator",
  },
  SD: {
    name: "South Dakota",
    abbreviation: "SD",
    state: true,
    numberOfDelegates: 1,
    houseName: "House of Representatives",
    houseRepName: "Representative",
    senateName: "Senate",
    senatorName: "Senator",
  },
  TN: {
    name: "Tennessee",
    abbreviation: "TN",
    state: true,
    numberOfDelegates: 9,
    houseName: "House of Representatives",
    houseRepName: "Representative",
    senateName: "Senate",
    senatorName: "Senator",
  },
  TX: {
    name: "Texas",
    abbreviation: "TX",
    state: true,
    numberOfDelegates: 38,
    houseName: "House of Representatives",
    houseRepName: "Representative",
    senateName: "Senate",
    senatorName: "Senator",
  },
  UT: {
    name: "Utah",
    abbreviation: "UT",
    state: true,
    numberOfDelegates: 4,
    houseName: "House of Representatives",
    houseRepName: "Representative",
    senateName: "Senate",
    senatorName: "Senator",
  },
  VT: {
    name: "Vermont",
    abbreviation: "VT",
    state: true,
    numberOfDelegates: 1,
    houseName: "House of Representatives",
    houseRepName: "Representative",
    senateName: "Senate",
    senatorName: "Senator",
  },
  VA: {
    name: "Virginia",
    abbreviation: "VA",
    state: true,
    numberOfDelegates: 11,
    houseName: "House of Delegates",
    houseRepName: "Delegate",
    senateName: "Senate",
    senatorName: "Senator",
  },
  VI: {
    name: "Virgin Islands",
    abbreviation: "VI",
    state: false,
    numberOfDelegates: 1,
    houseName: "Legislature of the Virgin Islands",
    houseRepName: "Senator",
    senateName: null,
    senatorName: null,
  },
  WA: {
    name: "Washington",
    abbreviation: "WA",
    state: true,
    numberOfDelegates: 10,
    houseName: "House of Representatives",
    houseRepName: "Representative",
    senateName: "Senate",
    senatorName: "Senator",
  },
  WV: {
    name: "West Virginia",
    abbreviation: "WV",
    state: true,
    numberOfDelegates: 3,
    houseName: "House of Delegates",
    houseRepName: "Delegate",
    senateName: "Senate",
    senatorName: "Senator",
  },
  WI: {
    name: "Wisconsin",
    abbreviation: "WI",
    state: true,
    numberOfDelegates: 8,
    houseName: "State Assembly",
    houseRepName: "Assemblymember",
    senateName: "State Senate",
    senatorName: "Senator",
  },
  WY: {
    name: "Wyoming",
    abbreviation: "WY",
    state: true,
    numberOfDelegates: 1,
    houseName: "House of Representatives",
    houseRepName: "Representative",
    senateName: "Senate",
    senatorName: "Senator",
  },
};
