export default {
  pledgeId: "keep_money_out_of_politics",
  version: "1.0.0",
  text: "keep money out of politics",
  shortText: "Keep money out of politics",
  weight: 30,
  subject: {
    voter: "Politicians should",
    influencer: "Politicians should",
    politician: "I commit to",
    government_worker: "I commit to",
    role_volunteer: "Politicians should",
  },
  subpledges: [
    {
      subPledgeId: "overturn_citizens_united",
      text: "support overturning Citizens United.",
      shortText: "Overturn Citizens United",
      weight: 20,
      version: "1.0.0",
    },
    {
      subPledgeId: "no_trading_assets",
      text: "not trade stocks, crypto, or other private financial assets while in office.",
      shortText: "No stock trading",
      weight: 15,
      version: "1.0.0",
    },
    {
      subPledgeId: "no_quid_pro_quo",
      text: "not engage in any quid pro quo or conflicts of interest.",
      shortText: "No quid pro quo",
      weight: 9,
      version: "1.0.0",
    },
    {
      subPledgeId: "pac_no_money",
      text: "take no money from PACs, corporations, or lobbyists.",
      shortText: "No PAC money",
      weight: 12,
      version: "1.0.0",
    },
    {
      subPledgeId: "pac_limited",
      text: "reject PAC, corporate, and lobbyist donations wherever possible, prioritizing small individual donors.",
      shortText: "Limited PAC money",
      weight: 5,
      version: "1.0.0",
    },
    {
      subPledgeId: "campaign_funds_usage",
      text: "use campaign contributions solely for campaign-related activities and official duties, not for personal benefit.",
      shortText: "Use campaign funds responsibly",
      weight: 6,
      version: "1.0.0",
    },
    {
      subPledgeId: "gift_restriction",
      text: "not accept gifts, trips, or favors (including dinners) from those seeking influence, including foreign governments, agents, or entities.",
      shortText: "No gifts",
      weight: 7,
      version: "1.0.0",
    },
    {
      subPledgeId: "post_office_lobbying",
      text: "not accept employment with lobbyists or regulated entities for 2 years after leaving office.",
      shortText: "No securing future jobs",
      weight: 3,
      version: "1.0.0",
    },
    {
      subPledgeId: "contracts_and_hiring_friends_family",
      text: "not award contracts or give jobs to friends, family, or favored companies.",
      shortText: "No hiring friends and family",
      weight: 4,
      version: "1.0.0",
    },
  ],
};
